In [1]:
import numpy as np
array = np.array([[[1,2],[3,4]],[[0,5],[6,7]]])

In [2]:
array

array([[[1, 2],
        [3, 4]],

       [[0, 5],
        [6, 7]]])

In [3]:
np.delete(array[:][:], 1, axis=2)

array([[[1],
        [3]],

       [[0],
        [6]]])

In [4]:
np.delete(array,0, axis=2)

array([[[2],
        [4]],

       [[5],
        [7]]])

In [5]:
np.delete(array,1,  axis=1)

array([[[1, 2]],

       [[0, 5]]])